// <auto-generated />
namespace BusinessCardManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initupdatedate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initupdatedate));
        
        string IMigrationMetadata.Id
        {
            get { return "202106151032371_init-update-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
